---
- name: install and configure basic environment
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- name: setup development environment
  hosts: development
  become: yes
  become_method: sudo
  roles:
    - git
    - tmux
    - vim

- name: install development tools
  hosts: development
  become: yes
  become_method: sudo
  roles:
    - dotnet
    - terraform

- name: install work configurations
  hosts: work
  become: yes
  become_method: sudo
  roles:
    - openvpn
