---
# Install and configure basic environment
- name: install basic packages
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

# configure work development environment
- name: install work packages
  hosts: work
  become: yes
  roles:
    - php
