---
- name: Clone pyenv repo
  ansible.builtin.git:
    dest: "{{ pyenv_dest }}"
    repo: "https://github.com/pyenv/pyenv.git"
  tags:
    - packages

- name: Set pyenv repo permissions
  ansible.builtin.file:
    group: "{{ user }}"
    owner: "{{ user }}"
    path: "{{ pyenv_dest }}"
    recurse: true
  tags:
    - config

- name: Enable dynamic bash extension
  shell: "./src/configure && make -C src"
  args:
    chdir: "{{ pyenv_dest }}"
  tags:
    - config

- name: Add pyenv to profile
  ansible.builtin.lineinfile:
    insertbefore: "if running bash"
    line: "{{ item }}"
    path: "{{ profile }}"
  with_items:
    - 'export PYENV_ROOT="{{ pyenv_dest }}"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init --path)"'
  tags:
    - config

- name: Add pyenv to bash profile
  ansible.builtin.lineinfile:
    line: 'eval "$(pyenv init -)"'
    path: "~/.bashrc"
  tags:
    - config

- name: Install Python versions
  shell: ". {{ profile }}; pyenv install -s {{ item }}"
  with_items: "{{ python_versions }}"
  register: pyenv_versions
  tags:
    - packages

- name: Set global python default versions
  shell: ". {{ profile }}; pyenv global {{ python_versions | join(' ') }}"
  tags:
    - config

- name: Install packages
  ansible.builtin.package:
    state: present
    name: "{{ lookup('community.general.flattened', python_packages) }}"
  tags:
    - packages

- name: install pip packages
  pip:
    name: "{{ pip_packages }}"
