---
- name: create nvm home
  ansible.builtin.file:
    group: "{{ group }}"
    path: "{{ lookup('env', 'HOME') }}/.nvm"
    owner: "{{ user }}"
    state: directory

- name: install nvm
  shell: "export PROFILE={{ profile }}; export NVM_DIR={{ lookup('env', 'HOME') }}/.nvm; curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
  tags:
    - packages

- name: Add nvm to shell
  ansible.builtin.lineinfile:
    line: "{{ item }}"
    path: "{{ profile }}"
  with_items:
    - 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm'
  tags:
    - config

- name: install node versions
  shell: ". {{ profile }}; nvm install {{ item }}"
  with_items: "{{ node_versions }}"
  tags:
    - packages

- name: set default node version
  shell: ". {{ profile }}; nvm alias default node"
  tags:
    - config
