---
- name: install git
  ansible.builtin.package:
    name: git
    state: latest
  tags:
    - packages

- name: create git directories
  ansible.builtin.file:
    group: "{{ group }}"
    mode: 0755
    owner: "{{ user }}"
    path: "{{ lookup('env', 'HOME') }}/.config/{{ item }}"
    state: directory
  with_items:
    - git
  tags:
    - config

- name: copy git config
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/.config/git/"
    group: "{{ group }}"
    mode: 0644
    owner: "{{ user }}"
    src: "{{ item }}"
  with_items:
    - config
  tags:
    - config

- name: download git lfs
  shell: "curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash"
  args:
    warn: false
  tags:
    - config

- name: install git lfs
  ansible.builtin.package:
    state: present
    name: git-lfs
  tags:
    - config
