---
- name: install tmux
  ansible.builtin.package:
    name: tmux
    state: latest
  tags:
    - packages

- name: copy files
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/"
    group: "{{ group }}"
    mode: 0644
    owner: "{{ user }}"
    src: "{{ item }}"
  with_items:
    - .tmux.conf
