---
- name: Install packages
  ansible.builtin.package:
    state: present
    name: "{{ lookup('community.general.flattened', os_packages, base_packages, personal_packages) }}"
  tags:
    - packages

# snap package manager not included in ansible.builtin.package
- name: install snap packages
  snap:
    name: "{{ snap_packages }}"
  tags:
    - packages

- name: install classic snap packages
  snap:
    name: "{{ classic_snap_packages }}"
    classic: yes
  tags:
    - packages
