---
- name: install vim
  ansible.builtin.package:
    name: vim
    state: latest
  tags:
    - packages

- name: create vim directories
  ansible.builtin.file:
    group: "{{ group }}"
    mode: 0755
    owner: "{{ user }}"
    path: "{{ lookup('env', 'HOME') }}/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload/
    - colors/
    - plugged/
  tags:
    - config

- name: install plugged package manager
  ansible.builtin.get_url:
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"
    group: "{{ group }}"
    mode: 0644
    owner: "{{ user }}"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - config

- name: install color theme
  ansible.builtin.get_url:
    dest: "{{ lookup('env', 'HOME') }}/.vim/colors/solarized.vim"
    group: "{{ group }}"
    mode: 0644
    owner: "{{ user }}"
    url: https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
  tags:
    - config

- name: copy files
  ansible.builtin.copy:
    dest: "{{ lookup('env', 'HOME') }}/.vim/"
    group: "{{ group }}"
    mode: 0644
    owner: "{{ user }}"
    src: "{{ item }}"
  with_items:
    - vimrc
  tags:
    - config
